### ISSUE TITLE
Fix Sponsors component to work in light mode

### ISSUE THREAD

**Issue by delucis** [volarjs/docs#3]
The current `Sponsors.astro` breaks in light mode:

| Dark | Light |
|---|---|
| <img width="583" alt="image" src="https://github.com/volarjs/docs/assets/357379/bc3dce1a-6b06-4cd1-b2f1-42680668ed13"> | <img width="584" alt="image" src="https://github.com/volarjs/docs/assets/357379/61402a70-2f63-4431-9086-3fcd424f6015"> |

Fixing https://github.com/volarjs/docs/blob/main/src/components/Sponsors.astro would be helpful!

**Comment by Princesseuh** [comment]
Fixed by https://github.com/volarjs/docs/pull/7
