### ISSUE TITLE
Expand file structure stub

### ISSUE THREAD

**Issue by delucis** [volarjs/docs#4]
The file structure page in the docs is currently a stub: https://volarjs.dev/guides/file-structure/

It would be good to expand this with proper content. Perhaps the starter project could be a good reference for putting this together: https://github.com/volarjs/starter

**Comment by Susmita-Dey** [comment]
Hey @delucis I'd like to give it a try

**Comment by Princesseuh** [comment]
Fixed by https://github.com/volarjs/docs/pull/9
